### ISSUE TITLE
建议增加Headers_User_Agent变量

### ISSUE THREAD

**Issue by yyyfffccc** [BNDou/Auto_Check_In#10]
大多数的抓包设备'User-Agent'与脚本中不一致，会导致cookie失效很快，所以建议设置成变量，抓包时顺带多复制一个，一劳永逸。虽然可以自己改脚本，但如果仓库更新就又得改一遍。仅个人需求建议。谢谢

**Comment by BNDou** [comment]
@yyyfffccc 好的，多谢提出建议，这一点我确实没有想到，今晚回去我更新一下😄

**Comment by yyyfffccc** [comment]
> @yyyfffccc 好的，多谢提出建议，这一点我确实没有想到，今晚回去我更新一下😄

多谢

**Comment by yyyfffccc** [comment]
> @yyyfffccc 只有User-Agent一个变量需要设置吗？如果没有其他的话就拉新一版吧，我已上传。 添加环境变量“USER_AGENT_ZHANGFEI”即可。 拉取指令也更新了一下，指令后面添加了指定拉取“main”分支。建议你修改一下，把本地原来的脚本文件夹删除重新拉一下，如果不改的话可能会拉取失败。

测试可用，多谢

**Comment by yyyfffccc** [comment]
@BNDou 可以更进一步把金丝篓数量也设置成变量，当然无关痛痒。只是觉得一晚三十个太多了。

**Comment by BNDou** [comment]
@yyyfffccc 已更新。
现在到0点都是用秒杀软件的，有时候抢不过别人，所以之前默认30个，概率或许会大一点，我是40个开出来的😂

**Comment by yyyfffccc** [comment]
> @yyyfffccc 已更新。 现在到0点都是用秒杀软件的，有时候抢不过别人，所以之前默认30个，概率或许会大一点，我是40个开出来的😂

感谢，我还没开出来，不过点券不够，买不来那么多金丝篓

**Comment by qq846511277** [comment]
> 

确实 我现在开30 已经出了三个号的霸天虎了

**Comment by BNDou** [comment]
> > 
> 
> 确实 我现在开30 已经出了三个号的霸天虎了

你试试把霸天虎删了再抽😂说不定就出来了

**Comment by qq846511277** [comment]
> > > 
> > 
> > 
> > 确实 我现在开30 已经出了三个号的霸天虎了
> 
> 你试试把霸天虎删了再抽😂说不定就出来了

我晚上试试，我看人家都是霸天虎后面就跟着雷诺的，或者公牛。

**Comment by zy-xiaoao** [comment]
> @yyyfffccc 好的，多谢提出建议，这一点我确实没有想到，今晚回去我更新一下😄

能加一个买金丝篓的包吗

**Comment by BNDou** [comment]
@zy-xiaoao 晚上回去我看看，先给你打个预防针这个估计不可行。因为掌飞本身不支持购买，我完了试试改包。

**Comment by BNDou** [comment]
@zy-xiaoao 试了不行，掌飞商城数据库没有金丝篓，识别不了，但是掌飞商城里面有的可以用，不过感觉没啥意义我就没上传。
