### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by jinjinv587** [BNDou/Auto_Check_In#16]
作者，我为啥报这个错误啊

Traceback (most recent call last):
  File "/ql/scripts/BNDou_Auto_Check_In_main/checkIn_ZhangFei_XunBao.py", line 364, in <module>
    main()
  File "/ql/scripts/BNDou_Auto_Check_In_main/checkIn_ZhangFei_XunBao.py", line 326, in main
    user_data['starId'], user_data['mapId'] = isdaji(user_data)
  File "/ql/scripts/BNDou_Auto_Check_In_main/checkIn_ZhangFei_XunBao.py", line 256, in isdaji
    soup = BeautifulSoup(response.text, 'lxml')
  File "/usr/lib/python3.9/site-packages/bs4/__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

## 执行结束... 2023-03-20 06:00:04 耗时 4 秒

**Comment by BNDou** [comment]
@jinjinv587 缺少lxml依赖，在“依赖管理”里面新建依赖就行
![Screenshot_2023-03-20-10-54-10-355-edit_com.android.browser.jpg](https://user-images.githubusercontent.com/67632799/226235957-dc9db0eb-55a5-4cdf-b3ab-f162b6c8f17a.jpg)

**Comment by jinjinv587** [comment]
我试了，老是安装失败，好奇怪啊，是我青龙版本有问题？

**Comment by BNDou** [comment]
> 我试了，老是安装失败，好奇怪啊，是我青龙版本有问题？

什么版本？确认依赖安装成功的话，应该没问题。其他脚本有报错吗？

**Comment by jinjinv587** [comment]
其他我就跑了掌飞签到，不报错，别的没跑，我的青龙2.11.3版本，要不加个v？913214983

**Comment by BNDou** [comment]
@jinjinv587 加你q了。我刚试了一下，好像就是版本的原因，说是找不到依赖版本，不过可以试试配置文件extra.sh里面指定源添加，如下：
![Screenshot_2023-03-20-11-31-52-334_com.android.browser.png](https://user-images.githubusercontent.com/67632799/226240370-9825228f-9ff9-434b-aee4-7405ea045415.png)

不过我不确定指定哪个版本的源，你要是想琢磨可以去试试。或者你可以安装两个版本的青龙，我docker里面装了一个旧版不更新，一个新版自动更新
