### ISSUE TITLE
掌飞签到异常

### ISSUE THREAD

**Issue by citizenzc** [BNDou/Auto_Check_In#21]
刚加上测试是好的，后面就不行了，我在签到页面抓的cookie😂麻烦大佬看下![Screenshot_20230505_211508_com.microsoft.emmx.png](https://user-images.githubusercontent.com/33755408/236468033-f85bc82f-a4df-4538-9eff-09f4c9ff8adf.png)

**Comment by BNDou** [comment]
@citizenzc ios还是安卓？目测安卓抓的比较稳当，苹果好像手机一登录就刷新了

**Comment by BNDou** [comment]
@citizenzc 你是不是切换账号了，或者切换大区、手游什么的，切换之后，token也可能会刷新。如果没有的话，可能你还是没抓对，referer这个也得重新抓喔，别忘了，cookie和这个一起抓

**Comment by BNDou** [comment]
@citizenzc 额，那你两个设备登录肯定会刷新的
