### ISSUE TITLE
金丝篓的推送有问题，无法推送，其他推送正常

### ISSUE THREAD

**Issue by citizenzc** [BNDou/Auto_Check_In#22]
![image](https://github.com/BNDou/Auto_Check_In/assets/33755408/6ecec6fe-4342-43c4-855e-58f92e6484cf)
![image](https://github.com/BNDou/Auto_Check_In/assets/33755408/5fbe9168-ac29-46e4-8cd5-fcff0f0836ce)
重新拉过库的，麻烦大佬看下

**Comment by BNDou** [comment]
@citizenzc 没问题的，只有开出霸天虎、公牛、雷诺才会推送

**Comment by BNDou** [comment]
@citizenzc 你可以看看源码(193行)，我只输出了出货消息log_push，开箱子过程中的消息msg只用做判断是否出货(179行)
