### ISSUE TITLE
掌飞签到

### ISSUE THREAD

**Issue by cyrus0w** [BNDou/Auto_Check_In#23]
添加环境变量COOKIE_ZHANGFEI、REFERER_ZHANGFEI、USER_AGENT_ZHANGFEI，多账号用回车换行分开

这几个参数值怎么获取呢？获取后怎么使用呢？

**Comment by BNDou** [comment]
@cyrus0w 进入签到界面，开启抓包，点击签到，返回抓包软件，就能找到，说白了就是把签到请求抓到就行了。使用的话，青龙直接添加环境变量。
