### ISSUE TITLE
为什么cookie失效阿

### ISSUE THREAD

**Issue by xqhyx** [BNDou/Auto_Check_In#25]
是我抓的不对吗？提供的三个关键词对上了阿
![Screenshot_2023-09-06-08-38-13-639_org mozilla firefox](https://github.com/BNDou/Auto_Check_In/assets/144187099/00622a4c-efb9-476a-b8cd-b9137082bdff)
![Screenshot_2023-09-06-08-37-28-477_com guoshi httpcanary premium](https://github.com/BNDou/Auto_Check_In/assets/144187099/3b8b209e-4e7f-400c-9f7a-0688e05e80cf)

**Comment by BNDou** [comment]
@xqhyx 我这个做的不好，当时只是为了攒积分抽内测，估计现在接口更新淘汰了。

**Comment by xqhyx** [comment]
谢谢解答
