### ISSUE TITLE
必应pc搜索失效.手机端正常使用.蹲一手能不能修复.拜托了

### ISSUE THREAD

**Issue by xqhyx** [BNDou/Auto_Check_In#26]
![Screenshot_2023-10-08-02-09-03-513_com microsoft bing](https://github.com/BNDou/Auto_Check_In/assets/144187099/b240478e-d7e9-47c1-9af4-7409c972ec84)

![Screenshot_2023-10-08-02-08-46-271_org mozilla firefox](https://github.com/BNDou/Auto_Check_In/assets/144187099/a07cc5bd-1bd4-4a66-9f1d-c7bee9030eed)

**Comment by BNDou** [comment]
@xqhyx 我记得是源码52行的search1里面的两个user_agent换一下就行了，不知道bing是怎么检查的，反正有时候不能用了就换一个，然后就又好使了。你小心封号，不知道是用脚本的问题还是换区的问题我的号已经凉了😂

**Comment by xqhyx** [comment]
@BNDou 没换区，用的日常手机的IP也会凉嘛，很多时候我都是手动执行的...希望不会吧.
