### ISSUE TITLE
掌飞寻宝相关问题

### ISSUE THREAD

**Issue by qq846511277** [BNDou/Auto_Check_In#29]
我发现掌飞寻宝还是有点小bug
![9H9V8}Z4I`D2C`SKTXHJT{B](https://github.com/BNDou/Auto_Check_In/assets/75515605/08823be7-2311-433e-a0eb-2d0ebde90a26)
![%7WSAY`U2%F{L6_LFPX%DLS](https://github.com/BNDou/Auto_Check_In/assets/75515605/a532aaa8-915f-410f-8736-b729c990367b)
如上图，凌晨运行显示无次数。8:47运行只能抽两次，实际上应该有五次机会

**Comment by BNDou** [comment]
@qq846511277 这个不是bug，次数是有规则的：

- 每日登录掌上飞车可获得3次寻宝机会，
- 紫钻玩家可额外获得1次，
- 每日登录游戏可获得1次寻宝机会”

共5次

0点卡服务器肯定是没次数，每月底不是清空点券让前十分钟不要领东西，所以我设置的签到0:10，寻宝0:10:30，这样最少也能有2次寻宝机会。

登录掌飞的那个包不知道是哪个，分析不出来，不然彻底解放了就

**Comment by qq846511277** [comment]
> @qq846511277 这个不是bug，次数是有规则的：
> 
> * 每日登录掌上飞车可获得3次寻宝机会，
> * 紫钻玩家可额外获得1次，
> * 每日登录游戏可获得1次寻宝机会”
> 
> 共5次
> 
> 0点卡服务器肯定是没次数，每月底不是清空点券让前十分钟不要领东西，所以我设置的签到0:10，寻宝0:10:30，这样最少也能有2次寻宝机会。
> 
> 登录掌飞的那个包不知道是哪个，分析不出来，不然彻底解放了就

对对对，我刚刚想说来着。如果能找到登录掌飞的包，就直接起飞了就，哈哈哈

照你这么说，签到算是登陆游戏咯？

**Comment by qq846511277** [comment]
> @qq846511277 这个不是bug，次数是有规则的：
> 
> * 每日登录掌上飞车可获得3次寻宝机会，
> * 紫钻玩家可额外获得1次，
> * 每日登录游戏可获得1次寻宝机会”
> 
> 共5次
> 
> 0点卡服务器肯定是没次数，每月底不是清空点券让前十分钟不要领东西，所以我设置的签到0:10，寻宝0:10:30，这样最少也能有2次寻宝机会。
> 
> 登录掌飞的那个包不知道是哪个，分析不出来，不然彻底解放了就

我好像找到那个包了，我你试试
[Stream 抓包记录 - bang.qq.com.txt](https://github.com/BNDou/Auto_Check_In/files/13103320/Stream.-.bang.qq.com.txt)

**Comment by BNDou** [comment]
@qq846511277 我的天呐伙计，你把数据都发出来了不怕网友盗号啊😂我把内容保存，那条回复先删了

**Comment by qq846511277** [comment]
好好好，那个接口 ping了之后 确实增加了3次寻宝次数，但是直接用脚本跑 还是显示没次数

**Comment by BNDou** [comment]
@qq846511277 这个是get请求，你不是写成post了吧😁中午我回去试试，手机上不好操作

**Comment by qq846511277** [comment]
这个参数跟Referer参数应该是一样的，我看他吧Referer当请求头一起放进去了

**Comment by BNDou** [comment]
@qq846511277 你ios怎么抓包，这都能逮着

**Comment by qq846511277** [comment]
ios有个Stream 免费的还挺好用，
之前我发现掌飞一开抓包进去就断网，这个版本好像不会了，
我一个页面一个页面试的 😁

**Comment by BNDou** [comment]
@qq846511277 不行，不是这个包，我这边是打开app时候发送的一个，然后寻宝次数就+3
这个请求不在页面里

**Comment by BNDou** [comment]
@qq846511277 我抓到了，但是data有加密，看不了内容😂抓下面这条url的请求

- https://api2.helper.qq.com/user/login

然后我第二天重新转发，寻宝次数+3

**Comment by qq846511277** [comment]
先开抓包 然后点开app吗

**Comment by BNDou** [comment]
@qq846511277 对的

**Comment by BNDou** [comment]
@citizenzc 代理的问题。
把前面那截儿代理换一个你能访问的就行了，或者你的网络要是可以直接访问github把代理删掉就好了。
