### ISSUE TITLE
貌似两个变量失效很快

### ISSUE THREAD

**Issue by yyyfffccc** [BNDou/Auto_Check_In#3]
掌上飞车一天后就会提示请重新刷新客户端

**Comment by qq846511277** [comment]
貌似当天失效

**Comment by BNDou** [comment]
> 掌上飞车一天后就会提示请重新刷新客户端

不应该呀，我这俩个月了也没过期，确定抓对了吧😂
有时候你切换账号或者切换大区登录后，里面的刷新令牌会变，所以可能会过期，我这俩个月没切换，一直能用

**Comment by yyyfffccc** [comment]
先试试看看

**Comment by qq846511277** [comment]
> > 掌上飞车一天后就会提示请重新刷新客户端
> 
> 不应该呀，我这俩个月了也没过期，确定抓对了吧😂 有时候你切换账号或者切换大区登录后，里面的刷新令牌会变，所以可能会过期，我这俩个月没切换，一直能用

你抓的是那个链接下得，(失效之后我重新抓包)我是发现那两个参数都没变化，会不会是抓包之后不能再上app了，上完就得重抓

**Comment by qq846511277** [comment]
> > 掌上飞车一天后就会提示请重新刷新客户端
> 
> 不应该呀，我这俩个月了也没过期，确定抓对了吧😂 有时候你切换账号或者切换大区登录后，里面的刷新令牌会变，所以可能会过期，我这俩个月没切换，一直能用

每次抓包之后 Referer 中 accessToken 会变

**Comment by BNDou** [comment]
@qq846511277 可以正常使用，只不过不要频繁切换账号或大区，我当时开发的时候切换大区后令牌也自动刷新了。掌飞前几天更新之后，我这还正常使用，也没过期

**Comment by qq846511277** [comment]
> @qq846511277 可以正常使用，只不过不要频繁切换账号或大区，我当时开发的时候切换大区后令牌也自动刷新了。掌飞前几天更新之后，我这还正常使用，也没过期

先试试看，

**Comment by qq846511277** [comment]
> > @qq846511277 可以正常使用，只不过不要频繁切换账号或大区，我当时开发的时候切换大区后令牌也自动刷新了。掌飞前几天更新之后，我这还正常使用，也没过期
> 
> 先试试看，

谢谢大佬

**Comment by yyyfffccc** [comment]
> @qq846511277 可以正常使用，只不过不要频繁切换账号或大区，我当时开发的时候切换大区后令牌也自动刷新了。掌飞前几天更新之后，我这还正常使用，也没过期

多谢，话说你们都永久雷诺开出了吗

**Comment by qq846511277** [comment]
> 话说你们都永久雷诺开

没有，我到现在还没全29呢

**Comment by qq846511277** [comment]
建议吧单开单个箱子的 data 加上

**Comment by BNDou** [comment]
@yyyfffccc 天数雷诺都攒了几十年了😂估计管够我玩，这个脚本就是前段时间封控在家没事干心血来潮玩玩，就用了一段时间，还没出货，我还是喜欢自己手动开箱子，比较有手感😄

**Comment by BNDou** [comment]
@qq846511277 代码里面有写吧，我刚刚抓包试了一下，好像这个版本掌飞有墙了，得root才能抓到关键数据，你是不是没抓全？代码里面用到的关键值我都有注释，应该没异常吧😂
![Screenshot_2023-01-11-15-40-36-452_com.github.android.png](https://user-images.githubusercontent.com/67632799/211747015-4b512c94-ffc6-47c7-88a3-c3f07e24ee64.png)
你看我刚刚重新抓的包也正常运行
![Screenshot_2023-01-11-15-53-26-704-edit_com.alibaba.android.rimet.jpg](https://user-images.githubusercontent.com/67632799/211748908-db12e990-9b15-45b6-888e-288cec5c4cef.jpg)

**Comment by qq846511277** [comment]
> @qq846511277 代码里面有写吧，我刚刚抓包试了一下，好像这个版本掌飞有墙了，得root才能抓到关键数据，你是不是没抓全？代码里面用到的关键值我都有注释，应该没异常吧😂 ![Screenshot_2023-01-11-15-40-36-452_com.github.android.png](https://user-images.githubusercontent.com/67632799/211747015-4b512c94-ffc6-47c7-88a3-c3f07e24ee64.png) 你看我刚刚重新抓的包也正常运行 ![Screenshot_2023-01-11-15-53-26-704-edit_com.alibaba.android.rimet.jpg](https://user-images.githubusercontent.com/67632799/211748908-db12e990-9b15-45b6-888e-288cec5c4cef.jpg)

是全的，运行没报错，不过我是ios 有的时候就是有莫名其妙的bug。那种直接可以开的宝箱，不需要钥匙的那种，他的data跟 金丝篓不一样

**Comment by BNDou** [comment]
@qq846511277 确实不同，这你就自己研究吧，我当时抓的钥匙宝箱那个页面，你可以试试，然后这个页面返回的referer链接放到电脑浏览器直接打开，f12抓一下，就能查看你这个页面里面道具代码和提交数据。这个开箱子应该还是post请求，按道理说规则一样，直接把钥匙那个data空下就行了

**Comment by qq846511277** [comment]
> @qq846511277 确实不同，这你就自己研究吧，我当时抓的钥匙宝箱那个页面，你可以试试，然后这个页面返回的referer链接放到电脑浏览器直接打开，f12抓一下，就能查看你这个页面里面道具代码和提交数据。这个开箱子应该还是post请求，按道理说规则一样，直接把钥匙那个data空下就行了

对，我自己有时间再折腾折腾吧，理论上就改下data 就行

**Comment by qq846511277** [comment]
> > @qq846511277 确实不同，这你就自己研究吧，我当时抓的钥匙宝箱那个页面，你可以试试，然后这个页面返回的referer链接放到电脑浏览器直接打开，f12抓一下，就能查看你这个页面里面道具代码和提交数据。这个开箱子应该还是post请求，按道理说规则一样，直接把钥匙那个data空下就行了
> 
> 对，我自己有时间再折腾折腾吧，理论上就改下data 就行

就怕掌飞的中奖率跟端游不是同步的

**Comment by BNDou** [comment]
@qq846511277 所以我改手动了，偷懒的话才启动脚本，存1千个金丝篓一个月就不用管了😂

**Comment by qq846511277** [comment]
> 

我先脚本跑10天吧

**Comment by yyyfffccc** [comment]
> > @qq846511277 可以正常使用，只不过不要频繁切换账号或大区，我当时开发的时候切换大区后令牌也自动刷新了。掌飞前几天更新之后，我这还正常使用，也没过期
> 
> 多谢，话说你们都永久雷诺开出了吗

今天上午抓的包晚上就失效了，能看下你们抓包的参数么？会不会我这边少了几个参数？

**Comment by qq846511277** [comment]
> 掌上飞车一天后就会提示请重新刷新客户端



> 

抓包之后 就别上app了，我测了昨晚抓的包到现在都没过期。还有最好吧ua 也换成自己手机的

**Comment by yyyfffccc** [comment]
> > 掌上飞车一天后就会提示请重新刷新客户端
> 
> > 
> 
> 抓包之后 就别上app了，我测了昨晚抓的包到现在都没过期。还有最好吧ua 也换成自己手机的

多谢，我重新抓包了也把ua换成手机的了，抓包后就退出了app，等明天再看看

**Comment by qq846511277** [comment]
我上次抓的 到期了，现在来看有效期1个月

**Comment by BNDou** [comment]
> 我上次抓的 到期了，现在来看有效期1个月

啥时候搞一搞自动登录，就不用抓了，肯定有办法
