### ISSUE TITLE
寻宝问题

### ISSUE THREAD

**Issue by YaChiLau** [BNDou/Auto_Check_In#30]
当天的Referer寻宝是没问题的，过了12点之后就提示寻宝次数用完了，再抓新的referer又可以寻宝了，这是要抓那一个才行呀

**Comment by BNDou** [comment]
@YaChiLau 寻宝次数每天共5次。

1. 每日登录掌上飞车可获得3次寻宝机会；
2. 紫钻玩家可额外获得1次；
3. 每日登录游戏可获得1次寻宝机会。

0点运行脚本提示没次数，那指定就是没紫钻和没登录游戏😂此时你上掌飞查看发现有3次，那是因为你已经登录掌飞了，这才获取的3次

**Comment by YaChiLau** [comment]
寻宝任务运行时间我设置了早上8点  掌飞签到的时间我没设置 是默认的时间， 昨昨晚我更新了referer 到了今天早上8点还是一样提示没次数😂

**Comment by BNDou** [comment]
@YaChiLau 正常的呀，因为你没登录掌飞。登录掌飞的包有加密，我解不开就没在签到里面添加这个接口，所以你签完还是没次数，这个需要自己登录一下掌飞才行，很麻烦，另一个ios端的大佬和我一起研究的寻宝，因为这个登录问题他果断放弃了哈哈哈。我自己是有紫钻的，完了每天12点有自动上号白嫖，所以我每天有两次寻宝机会😂

然后我还有个通知：
我准备把referer这个环境变量删了，感觉cookie里面和他里面的都差不多，寻宝的环境变量最核心的就是token，等我改好了，环境变量referer就可以删了

**Comment by YaChiLau** [comment]
@BNDou 嗦嘎 我懂了 感谢大佬的解答

**Comment by BNDou** [comment]
@YaChiLau 我更新了，你拉一下库吧，环境变量和签到的一样，内容稍微调整了一下，基本上没变化。

后续如果新增消费劵买东西的话，参数也只会在cookie里面新增，昨晚扣了一晚上数据，目前测试阶段没有新增参数

**Comment by YaChiLau** [comment]
@BNDou 那太棒了！ 感谢大佬  我去备份一下推送文件就重新拉

**Comment by YaChiLau** [comment]
@BNDou 还有一个问题  就是推送的话是用哪一个文件 .py还是.js

**Comment by BNDou** [comment]
@YaChiLau 我记得是py，文件头部有我的注释

**Comment by YaChiLau** [comment]
@BNDou 脚本里标注了.py文件，已经弄好了,感谢大佬😗
