### ISSUE TITLE
为什么我签到正常，寻宝和金丝篓就不行，寻宝是有四次的😳麻烦帮忙看下

### ISSUE THREAD

**Issue by citizenzc** [BNDou/Auto_Check_In#31]
![mmexport1699280006191.png](https://github.com/BNDou/Auto_Check_In/assets/33755408/4261d1e8-f26b-4706-961a-e2d12801de42)

**Comment by BNDou** [comment]
@citizenzc 更新代码没？😂前段时间更新有点频繁，可能你正好没同步到，顺便检查一下新的环境变量，这几个脚本和环境变量现在已经都固定完善了，暂时后面不会有改动。

**Comment by BNDou** [comment]
@citizenzc 可以的话我加你看看
