### ISSUE TITLE
购物问题

### ISSUE THREAD

**Issue by chendada00** [BNDou/Auto_Check_In#32]
![image](https://github.com/BNDou/Auto_Check_In/assets/53457984/e4b5c351-4019-4818-af91-c28c920fdf42)
是我缺了什么东西吗

**Comment by BNDou** [comment]
@chendada00 你这个情况确实我的代码也有问题，回头我调整一下，不过环境变量如果正确的话，应该不会报错。

你暂时确认一下环境变量是不是按照文件头部注释规定写的，确认一下以下这几个字段是否正确

- roleId，userId，areaId，token

这个情况就是因为参数不正确，导致的查询结果为空，所以先请核对下信息~

**Comment by chendada00** [comment]
掌飞的cookie多久掉线一次呀，目前签到和开箱都没问题，那个寻宝不行

**Comment by chendada00** [comment]
刚检查了下好像都没啥问题

**Comment by BNDou** [comment]
@chendada00 安卓需要每月换一次，ios好像登录就刷新（最好别登录）
我可以加你q看看吗

**Comment by chendada00** [comment]
可以2207117672
