### ISSUE TITLE
开大闸蟹

### ISSUE THREAD

**Issue by chendada00** [BNDou/Auto_Check_In#33]
改成多线程之后失败的概率太高了，五次就成功一次
![image](https://github.com/BNDou/Auto_Check_In/assets/53457984/a2de676a-fcd9-4dde-a994-0246ee002226)

**Comment by BNDou** [comment]
@chendada00 没办法，掌飞接口就是这样，容易频繁

要想开得快不频繁只能在游戏内开（抓内存秒开）😂之前不是分享了一个游戏内邮箱的[快捷指令](https://github.com/BNDou/Auto_Check_In/blob/main/feiche_code.md)，就是利用内存秒开的

信不过自己能否卡准时间的话，再一个办法就是直接用秒开软件

**Comment by chendada00** [comment]
快捷指令是不是被和谐了呀，我前几天试了下好像发不了了
