### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by chendada00** [BNDou/Auto_Check_In#34]
登录好像有点问题，显示登录成功，但是寻宝次数就一次
![image](https://github.com/BNDou/Auto_Check_In/assets/53457984/b3dbeba2-3cbf-43a0-8340-e152d184bdd6)
![image](https://github.com/BNDou/Auto_Check_In/assets/53457984/24354e32-8026-4a70-a716-cae16e814aa8)

**Comment by BNDou** [comment]
@chendada00 不太清楚了，我这儿测试没问题，昨天更新代码了，你可以更新一下。

不过这里判断是否登录成功的条件还不完善，这里返回的登录成功是我写死的，这个判断条件貌似只是判断token是否有效。

不过登录请求是没问题的，我这里两号都成功了，你再检查一下login的包解码是否正确。

确定正确的话，可以用pc端浏览器尝试打开`https://bang.qq.com/app/speed/treasure/index?roleId=QQ号&areaId=1或2即电信或联通&uin=QQ号`这个链接，查看刷新页面上的次数。

有时候可能因为延迟问题导致没有更新出来，当然以上都是建立在login的data请求体的正确解码上才成立。

**Comment by chendada00** [comment]
是把那个加密的拿出来用base64编码一下就可以吗，我有点没太看懂那个脚本里面的说明

**Comment by chendada00** [comment]
可以了，看来不能把乱码复制出来再用base64编码，只能用fiddler直接编码

**Comment by BNDou** [comment]
> 可以了，看来不能把乱码复制出来再用base64编码，只能用fiddler直接编码

👌🏻nice
