### ISSUE TITLE
中了中了！

### ISSUE THREAD

**Issue by qq846511277** [BNDou/Auto_Check_In#4]
![(RMO@DMGA@G1%$PI 5HEGM5](https://user-images.githubusercontent.com/75515605/216485423-09337383-f033-46e9-b835-b92583057e5e.png)

**Comment by BNDou** [comment]
哪呢，没有吧😂

**Comment by qq846511277** [comment]
每次0点都是开箱失败

**Comment by qq846511277** [comment]
![image](https://user-images.githubusercontent.com/75515605/216739290-fc0d0e72-b3cb-4724-864e-4f9bea534526.png)

**Comment by BNDou** [comment]
> ![image](https://user-images.githubusercontent.com/75515605/216739290-fc0d0e72-b3cb-4724-864e-4f9bea534526.png)
> 

我两个月出了3次公牛🤣雷诺就是不来
兄台你这实践证明脚本还是可行的 哈哈哈

**Comment by BNDou** [comment]
> 每次0点都是开箱失败

你是不是分好几个任务开始运行的，每个任务开5个，掌飞这个请求频繁了就会报异常，我之前弄了多线程一直报超时，最后就删了

**Comment by qq846511277** [comment]
没问题啊 直接置顶！！！

**Comment by qq846511277** [comment]
> > 每次0点都是开箱失败
> 
> 你是不是分好几个任务开始运行的，每个任务开5个，掌飞这个请求频繁了就会报异常，我之前弄了多线程一直报超时，最后就删了

直接 while True: 
try：
一直请求开箱子

**Comment by qq846511277** [comment]
原来楼主也圆梦了啊

**Comment by BNDou** [comment]
> 原来楼主也圆梦了啊

下一个目标针尖😄

**Comment by qq846511277** [comment]
![)}DE73@BD2QSJPS7{ `72}C](https://user-images.githubusercontent.com/75515605/223887729-cccc1479-618b-438f-9051-04b3016fe724.png)
真亏啊！昨晚战绩，四个号，两个公牛，一个霸天虎
