### ISSUE TITLE
脚本猫怎么获取cookie呀。浏览器F12获取一直报错

### ISSUE THREAD

**Issue by mem4tgo** [BNDou/Auto_Check_In#47]
脚本猫怎么获取cookie呀。浏览器F12获取一直报错

**Comment by mem4tgo** [comment]
Traceback (most recent call last):
  File "/ql/data/scripts/renren/checkIn_ScriptCat.swap.py", line 125, in <module>
    log += ScriptCat(cookie_ScriptCat[i]).main()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/renren/checkIn_ScriptCat.swap.py", line 100, in main
    self.get_log()
  File "/ql/data/scripts/renren/checkIn_ScriptCat.swap.py", line 95, in get_log
    self.date = html.xpath('//p[3]/font//text()')[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by BNDou** [comment]
@mem4tgo 抓取签到页面的url = "https://bbs.tampermonkey.net.cn/plugin.php?id=dsu_paulsign:sign"的请求，把这个请求的cookie做环境变量试试

**Comment by mem4tgo** [comment]
> @mem4tgo 抓取签到页面url的请求 `https://bbs.tampermonkey.net.cn/plugin.php?id=dsu_paulsign:sign` 把这个请求的cookie做环境变量试试

Traceback (most recent call last):
  File "/ql/data/scripts/renren/checkIn_ScriptCat.py", line 125, in <module>
    log += ScriptCat(cookie_ScriptCat[i]).main()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/renren/checkIn_ScriptCat.py", line 100, in main
    self.get_log()
  File "/ql/data/scripts/renren/checkIn_ScriptCat.py", line 95, in get_log
    self.date = html.xpath('//p[3]/font//text()')[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by mem4tgo** [comment]
还是不行

**Comment by mem4tgo** [comment]
_dx_app_captchadiscuzpluginbydingxiang2017=668d3dsqB87zJ1; _dx_captcha_cid=811484; _dx_FMrPY6=668d3d1cUsnBxCsqB87zJ1; _dx_uzZo5y=3b1d6441f8b7fe92820a42dc79f37e5; sl-session=4mhDm+iKjtw==; PHPSESSID=121c4f8eea1f96cfbb5924ae23f; B6hk_2132_pc_size_c=0; B6hk_2132_sid=Zx77mI; B6hk_2132_saltkey=x9H8app2; B6hk_2132_lastvisit=1720607617; _dx_captcha_vid=390EE3818BD9DFBDB8B2B80; B6hk_2132_ulastactivity=3ceayTQe7GQfB5cRg3FG9zTh3H; B6hk_2132_auth=51b35Z%2Fb2XiEGDjfF5DPmbCAwAY5fFPL1VZtelCuYO5g; B6hk_2132_lip=111.34%2254; B6hk_2132_connect_is_bind=0; B6hk_2132_noticeTitle=1; B6hk_2132_nofavfid=1; B6hk_2132_st_p=142349%7a3872; B6hk_2132_visitedfid=94; B6hk_2132_viewid=tid_7301; B6hk_2132_smile=4D1; B6hk_2132_lastcheckfeed=14234720611405; _ga_ZNEX8R=GS1.1..0.0; B6hk_2132_lastact=17422%09misc.php%09patch

**Comment by BNDou** [comment]
@mem4tgo 方便q或v吗，我需要登录你的号试试

**Comment by BNDou** [comment]
@mem4tgo 我知道原因了，一定要抓取签到请求，url是
 
`https://bbs.tampermonkey.net.cn/plugin.php?id=dsu_paulsign:sign`

把这个请求的cookie做环境变量试试。
刚刚我筛去了无用的cookie，也就是只需要这俩个值就能签到
`B6hk_2132_saltkey=xxxx; B6hk_2132_auth=xxxx;`
