### ISSUE TITLE
夸克签到挂了应该是签到修改参数了

### ISSUE THREAD

**Issue by shusheng110** [BNDou/Auto_Check_In#48]
夸克签到挂了应该是签到修改参数了，求修复

**Comment by BNDou** [comment]
@shusheng110 确实接口参数有变动，我刚更新了一版，用移动端抓包。先测试几天，看看参数有效期大概多长时间。

- 【手机端】抓包流程

1. 打开抓包，手机端访问签到页

2. 找到url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息

3. 复制url后面的参数: kps sign vcode 粘贴到环境变量

环境变量名为 `COOKIE_QUARK` 多账户用 `回车` 或 `&&` 分开，例如: 

```
user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
```

> user字段是用户名 (可是随意填写，多账户方便区分)

**Comment by Martinxux** [comment]
> @shusheng110 确实接口参数有变动，我刚更新了一版，用移动端抓包。先测试几天，看看参数有效期大概多长时间。
> 
> * 【手机端】抓包流程
> 
> 1. 打开抓包，手机端访问签到页
> 2. 找到url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息
> 3. 复制url后面的参数: kps sign vcode 粘贴到环境变量
> 
> 环境变量名为 `COOKIE_QUARK` 多账户用 `回车` 或 `&&` 分开，例如:
> 
> ```
> user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
> ```
> 
> > user字段是用户名 (可是随意填写，多账户方便区分)

是直接放到之前的Cookie后面吗，如果字段里面本来就包含'='怎么办呢

**Comment by BNDou** [comment]
@Martinxux 如果之前的cookie你没有其他用途的话，可以清空了，现在只需要三个字段就能签到，其中 `user` 字段是我为了多账号方便区分自定义的

```
user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
```

**Comment by penxian** [comment]
用啥工具抓包的

**Comment by BNDou** [comment]
@penxian 安卓机我用[ProxyPin](https://github.com/wanghongenpin/network_proxy_flutter)和小黄鸟或者fiddler都可以抓，前提是要root，ios没试过

**Comment by AfanChang** [comment]
![E60AB786-50AE-4F4C-A2CA-364B0278858D](https://github.com/user-attachments/assets/92a4d222-5ae8-416b-9897-7e5c0035cbd6)使用了那三个参数签到还是失败呢

**Comment by BNDou** [comment]
@AfanChang 那就是你没抓对，我抓的4个号都没问题
![Screenshot_2024-07-16-09-47-28-741_com.android.browser-edit.jpg](https://github.com/user-attachments/assets/114e71f0-6297-43d7-bf0e-fbc4f445fe84)

**Comment by AfanChang** [comment]
感谢，已解决，换了个抓包工具

**Comment by honeyallen321** [comment]
> @penxian 安卓机我用[ProxyPin](https://github.com/wanghongenpin/network_proxy_flutter)和小黄鸟或者fiddler都可以抓，前提是要root，ios没试过

IOS用stream
