### ISSUE TITLE
夸克签到bug反馈

### ISSUE THREAD

**Issue by wsjwqq** [BNDou/Auto_Check_In#49]
# Bug：
* checkIn_Quark.py V2版182行，main函数中处理cookie_quark的代码：
  `user_data.update({a.split('=')[0]: unquote(a.split('=')[1])})`

* 若`cookie_quark`中的`kps`字段为：`kps=xxxx==;`或`kps=xxxx=;`格式，
  原代码会将末尾的`==`或者`=`去除。
```python
# 原代码：
user_data = {}  # 用户信息
for a in cookie_quark[i].replace(" ", "").split(';'):
    if not a == '':
        user_data.update({a.split('=')[0]: unquote(a.split('=')[1])})      # <--------------------Bug代码
```
# 修复：
* 在chatgpt的帮助下修改成这样可以正常使用，不太懂python，不知道这样是否妥当。
```python
# 修复后代码：
user_data = {}  # 用户信息
for a in cookie_quark[i].replace(" ", "").split(';'):
    if not a == '':
        key, value = a.split('=', 1)
        user_data.update({key.strip(): unquote(value.strip())})
```

**Comment by BNDou** [comment]
@wsjwqq 确实没考虑到这个问题。这是因为抓包数据的不同导致的，我抓的数据是从url里面复制的，它是经过url编码后得到的，也就是 `=` 这种符号会变成 `%3D`，而你抓的数据可能是从header里面复制的数据，她是没有编码的，所以出现了这个情况，你可以去看看你的数据包中request url全拼，里面的参数都是结果编码转换后的，没有 `=` 。感谢指摘，晚点我去修改一下。
