### ISSUE TITLE
小米社区

### ISSUE THREAD

**Issue by moshi888** [BNDou/Auto_Check_In#5]
小米社区是要抓签到的包吗？没找到啊，有没有好心人发个链接啊？如果抓登录的包可以吗？

**Comment by BNDou** [comment]
@moshi888 随便访问一个帖子就能抓到，不过只有24小时有效，之后就过期了，其实没啥用😂

**Comment by moshi888** [comment]
那有没有什么方式比较久啊？24小时那24小时就得抓一次

**Comment by BNDou** [comment]
@moshi888 所以说没啥用（不过方法肯定有，类似jdcookie可以用wskey来刷新，但是我能力有限，如果有大佬会的话可以提交一版😄）。开始这个脚本是在13发布的时候写的，当时就是想着刷成长值领东西又不想每天繁琐的做任务，现在活动结束了，成长值任务也没几个，不值得每天抓包😃

**Comment by moshi888** [comment]
主要是我遇到过很多别的，他们直接抓ua，但是好像过不了验证码会提示需要短信登录 如果自动刷就完美了

**Comment by BNDou** [comment]
> 主要是我遇到过很多别的，他们直接抓ua，但是好像过不了验证码会提示需要短信登录 如果自动刷就完美了

这个我试过，抓到的数据太乱了研究不明白😅

**Comment by moshi888** [comment]
目前的有效期只有24小时吗？
