### ISSUE TITLE
环境变量这样设置问题出在哪里呢？

### ISSUE THREAD

**Issue by Myuuer** [BNDou/Auto_Check_In#50]
<img width="1280" alt="ql" src="https://github.com/user-attachments/assets/0e9aa09b-d251-48e1-9b22-febd9c348a6a">
第一次使用青龙。脚本已经导入，环境变量这样设置问题出在哪里呢，还需要改其它位置吗？

**Comment by BNDou** [comment]
@Myuuer 应该是大家cookie编码不同的问题，代码已更新，你重新去订阅更新一下，应该解决了

**Comment by Myuuer** [comment]
@BNDou 可以了哈哈，有点尴尬，我一直以为是环境设置的问题，或者要改脚本内容什么的。之前看到日志没注意，现在看到原来是缺少requests模块。

**Comment by BNDou** [comment]
@Myuuer 👌🏻好的
