### ISSUE TITLE
夸克添加变量后出现错误

### ISSUE THREAD

**Issue by Xingxiwei** [BNDou/Auto_Check_In#54]
✅ 检测到共 1 个夸克账号

Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 204, in <module>
    main()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 187, in main
    log = Quark(user_data).do_sign()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 159, in do_sign
    log += f"❌ 签到异常: 获取成长信息失败"
    ^^^
UnboundLocalError: cannot access local variable 'log' where it is not associated with a value
，请问如何解决是什么意思呢

**Comment by BNDou** [comment]
@Xingxiwei 三个参数肯定没弄对

**Comment by Xingxiwei** [comment]
> @Xingxiwei 三个参数肯定没弄对

三个参数，提示只要设置ck啊，请教还有填写那些参数呢？

**Comment by BNDou** [comment]
@Xingxiwei 就是说cookie里面那必要的三个参数，你可能没弄对，不妨把你的抓包请求发出来看看，url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息

**Comment by Xingxiwei** [comment]
{
&nbsp; &nbsp; "status": 401,
&nbsp; &nbsp; "code": 31001,
&nbsp; &nbsp; "message": "require login [guest]",
&nbsp; &nbsp; "req_id": "99m1wi-232e5c8c1dd8d3",
&nbsp; &nbsp; "timestamp": 1722244944
}

&nbsp;


Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月29日(星期一) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BNDou/Auto_Check_In] 夸克添加变量后出现错误 (Issue #54)














 
@Xingxiwei 就是说cookie里面那必要的三个参数，你可能没弄对，不妨把你的抓包请求发出来看看，url为 https://drive-m.quark.cn/1/clouddrive/capacity/growth/info 的请求信息

**Comment by Xingxiwei** [comment]
请问有tg吗？可以加下直接沟通吗？




Hey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BNDou/Auto_Check_In"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BNDou/Auto_Check_In] 夸克添加变量后出现错误 (Issue #54)





 
@Xingxiwei 就是说cookie里面那必要的三个参数，你可能没弄对，不妨把你的抓包请求发出来看看，url为 https://drive-m.quark.cn/1/clouddrive/capacity/growth/info 的请求信息

**Comment by BNDou** [comment]
我主页有链接，你加我吧
