### ISSUE TITLE
夸克抓包失败

### ISSUE THREAD

**Issue by AriesIce** [BNDou/Auto_Check_In#55]
开着抓包软件,进签到页面直接进不去显示网络错误,有啥其他办法抓包吗

**Comment by BNDou** [comment]
@AriesIce 常用安卓机需要满足下面的条件才能抓

1. 安卓机要root

2. ca证书要装到系统证书里面，而非用户证书

小白不建议root，刷机有风险，可以在电脑上试试虚拟机，具体教程就查阅网络资源吧
