### ISSUE TITLE
夸克能否添加每日抽奖

### ISSUE THREAD

**Issue by formyangel1219** [BNDou/Auto_Check_In#56]
偶尔能抽到1G，2G，5G的永久空间，还是很香的

**Comment by BNDou** [comment]
好的，明天我试一下

**Comment by formyangel1219** [comment]
感谢，每天可以抽3次，看页面进去后次数为0，然后变成3，应该先有请求查询可以抽的次数，再进行抽奖

**Comment by BNDou** [comment]
@formyangel1219 有点难度啊，抽奖次数的接口写好了。抽奖接口不行，需要用到一个抽奖订单号，每次抽奖都不一样，我逆向学的不好，所以不知道这个算法怎么整。抽奖暂时就先不搞了吧😂

**Comment by formyangel1219** [comment]
好吧，不过你用的哪个抓包工具，我用手机vnet搜索挺麻烦的，电脑没有好用的，有空可以一起交流研究

**Comment by BNDou** [comment]
@formyangel1219 安卓机我用的[ProxyPin](https://github.com/wanghongenpin/network_proxy_flutter)或PC端的Fiddler，前提是要root。IOS端网友说用stream，我没用过，就不清楚了
