### ISSUE TITLE
synology chat通知

### ISSUE THREAD

**Issue by 1983shake** [BNDou/Auto_Check_In#57]
作者你好，由于pushPlus的使用需要实名认证，且还需缴纳1元认证费。
我担心身份信息的不安全，因此在自家群晖上安装了chat，并且实现了青龙与chat的链接。

所以希望能将群晖的chat通知功能加入。谢谢。

**Comment by BNDou** [comment]
@1983shake 你好，我看了一下青龙自带通知模块有chat推送，所以刚刚把通知模块改为青龙自带通知了，你更新一下订阅运行试试。

**Comment by 1983shake** [comment]
谢谢大佬，已经通知到了。
