### ISSUE TITLE
夸克签到，提示签到异常: 获取成长信息失败 用户需要登录后才可访问

### ISSUE THREAD

**Issue by Joker319** [BNDou/Auto_Check_In#60]
你好，我在青龙执行夸克签到，运行后提示“签到异常: 获取成长信息失败 用户需要登录后才可访问”，请问是我哪一步设置有错误吗？
![1725324097827](https://github.com/user-attachments/assets/ab48265b-b907-4807-ac78-0851f95af3ee)

**Comment by BNDou** [comment]
@Joker319 cookie设置的参数可能没弄对

**Comment by BNDou** [comment]
@Joker319 

## 【手机端】抓包流程

1. 打开抓包，手机端访问签到页

2. 找到url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息

3. 复制url后面的参数: kps sign vcode 粘贴到环境变量

环境变量名为 `COOKIE_QUARK` 多账户用 `回车` 或 `&&` 分开，例如: 

```
user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
```

> user字段是用户名 (可是随意填写，多账户方便区分)

**Comment by Joker319** [comment]
你好，一定是要手机端吗？我填写的是网页端查的cookie
![1725328327412](https://github.com/user-attachments/assets/9ea16bf2-ea1d-4e7c-a088-671ed16d1395)

**Comment by BNDou** [comment]
@Joker319 网页端的接口官方已经修改了或者已经关闭了，目前只能用移动端。

如果你的设备不能抓包的话，可以试试虚拟机，抓到的这三个值目测有效期很长很长不过期，之后卸载掉也还有效。

有条件的话可以试试！

**Comment by Joker319** [comment]
根据你手机抓包的方法，已经成功签到了，十分感谢答疑解惑！

**Comment by Joker319** [comment]
最后想问问，现在有没有能用的阿里网盘签到脚本？现在阿里签到好像都不行

**Comment by BNDou** [comment]
@Joker319 没有喔，貌似全网都没啦😔

**Comment by Joker319** [comment]
明白了，十分感谢~！

**Comment by BNDou** [comment]
@Joker319 不客气的~什么时候有路子的话我会上传一版代码的😄
