### ISSUE TITLE
PushMe不推送

### ISSUE THREAD

**Issue by L7132** [BNDou/Auto_Check_In#61]
[utils/notify.py](https://github.com/BNDou/Auto_Check_In/blob/main/utils/notify.py)感觉还是缺少了一些通知方式，在换成[notify_new.py](https://github.com/user-attachments/files/17095193/notify_new.py.json)之后，推送正常了。

还望开发者更新一下代码！

**Comment by BNDou** [comment]
@L7132 感谢大佬建议！我已同步并注明来源，感谢！
![update](https://github.com/user-attachments/assets/d4b89c36-a83b-4b8c-93d3-64e2c862ada2)

**Comment by L7132** [comment]
![09242309](https://github.com/user-attachments/assets/1fec1b80-0a9c-40fc-a749-686343336398)
纯user，CV之后测试正常，于是来这里反馈罢了。😁

**Comment by BNDou** [comment]
哈哈哈还是不错的，让我接触到了新的推送工具，还蛮好用的

**Comment by L7132** [comment]
是这样的，我其他脚本推送也是pushme。🤗
