### ISSUE TITLE
夸克签到执行报错

### ISSUE THREAD

**Issue by yingerson** [BNDou/Auto_Check_In#63]
大家好，今天第一次进来。拉库以后手机端app抓包了参数后配置了COOKIE_QUARK变量，但是手动运行夸克签到，提示报错。
## 开始执行... 2024-10-17 14:43:51

----------夸克网盘开始签到----------
✅ 检测到共 1 个夸克账号

Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 227, in <module>
    main()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 210, in main
    log = Quark(user_data).do_sign()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 174, in do_sign
              ^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 137, in queryBalance
    balance = self.queryBalance()
           ~~~~~~~~^^^^^^^
KeyError: 'msg'    return response["msg"]


## 执行结束...   耗时 2 秒　　　

请问这个问题应该如何解决啊？

**Comment by BNDou** [comment]
@yingerson 重新拉库，再运行试试，应该没问题了。

**Comment by yingerson** [comment]
> @yingerson 重新拉库，再运行试试，应该没问题了。
重新拉库以后运行提示如此，我手机上抓包的时候自动签到了，不知道异常和这个有没有关系?
## 开始执行... 2024-10-17 16:08:24

----------夸克网盘开始签到----------
✅ 检测到共 1 个夸克账号

夸克自动签到

🙍🏻‍♂️ 第1个账号❌ 签到异常: 获取成长信息失败




PUSHPLUS 服务启动
PUSHPLUS 推送成功！
----------夸克网盘签到完毕----------

## 执行结束...   耗时 2 秒

**Comment by BNDou** [comment]
@yingerson 和已签到没关系，这个情况是参数没抓对，按照流程再试试~

## 【手机端】抓包流程

1. 打开抓包，手机端访问签到页

2. 找到url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息

3. 复制url后面的参数: kps sign vcode 粘贴到环境变量

环境变量名为 `COOKIE_QUARK` 多账户用 `回车` 或 `&&` 分开，例如: 

```
user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
```

> user字段是用户名 (可是随意填写，多账户方便区分)

**Comment by yingerson** [comment]
> @yingerson 和已签到没关系，这个情况是参数没抓对，按照流程再试试~
> 
> ## 【手机端】抓包流程
> 1. 打开抓包，手机端访问签到页
> 2. 找到url为 `https://drive-m.quark.cn/1/clouddrive/capacity/growth/info` 的请求信息
> 3. 复制url后面的参数: kps sign vcode 粘贴到环境变量
> 
> 环境变量名为 `COOKIE_QUARK` 多账户用 `回车` 或 `&&` 分开，例如:
> 
> ```
> user=张三; kps=abcdefg; sign=hijklmn; vcode=111111111;
> ```
> 
> > user字段是用户名 (可是随意填写，多账户方便区分)

## 开始执行... 2024-10-17 17:19:32

----------夸克网盘开始签到----------
✅ 检测到共 1 个夸克账号

夸克自动签到

🙍🏻‍♂️ 第1个账号❌ 签到异常: 获取成长信息失败




PUSHPLUS 服务启动
PUSHPLUS 推送成功！
----------夸克网盘签到完毕----------

## 执行结束...   耗时 2 秒　　　　　

我重新抓过了还是这样提示。
抓包是如下内容：https://drive-m.quark.cn/1/clouddrive/capacity/growth/info?__t=1729156598406&sign_cyclic=true&kps=LuGnTs+Es2kMDk95rqn9P/fKiwsuo5t5ZV5O0Hd48AO3KWc4dsXsGLpOxUd+DkP1mhlWhg5UDOPJmbOVSqL4sSrHLv2jl/1cU/ASZVT79dJzdQ==&sign=LuHBfuNRJHEshFOzAxmdyO6C1+/gwEW6DtPUq2MsLY+kM10WapbpACE+CIs86EO5h0E=&vcode=1729156598379&uc_param_str=dnfrpfbivessbtbmnilauputogpintnwmtsvcppcprsnnnchmicckp&dn=63279819426-d6dc5195&fr=iphone&pf=200&bi=997&ve=7.3.6.2241&ss=414x736&bt=UC&bm=WWW&ni=bTkwBcrKqfmhBXCNmWOGEPcLaCgORwjUwAVsQ9n128d7cF4=&la=zh-cn&ut=LuFBXFAgZmiD+RfLqAQCmpgjoLdmaCIY5lV4sNff4o6Qug==&og=GR&pi=1242x2208&nt=2&nw=WIFI&mt=W60B1oZLPD7uwBKSmCyed+tfLcGLK9uX&sv=appa&pc=LuHd1Zq5AMm7NvZqz9EezdqW5ektDR4lOzXE3WipJBema5IqySv3D9uCEtijvX4Z89XlhWHiZ8zy6vP0wM8X3MBq&pr=ucpro&nn=LuHdh+xuOzn1C0zzJz2GeL8c4GhH3HS+/MOOIsFY/SuJ4w==&ch=kk@appstore&mi=iPhone10,2&kp=LuGnTs+Es2kMDk95rqn9P/fKiwsuo5t5ZV5O0Hd48AO3KWc4dsXsGLpOxUd+DkP1mhlWhg5UDOPJmbOVSqL4sSrHLv2jl/1cU/ASZVT79dJzdQ==

环境变量我是这样写的：
![image](https://github.com/user-attachments/assets/4b11eea1-605d-4cd4-a6a8-b472774a1eb1)

**Comment by yingerson** [comment]
> @yingerson 把你填入的值中的 `&` 符号替换成 英文分号 `;`

感谢大大，已经解决了，太棒！

**Comment by BNDou** [comment]
😃客气啦，互相学习
