### ISSUE TITLE
掌飞参数

### ISSUE THREAD

**Issue by MySummerEgg** [BNDou/Auto_Check_In#65]
大佬,掌飞参数我抓包是全加密的,要怎么解密拿到返回的数据明文

**Comment by BNDou** [comment]
@MySummerEgg 我刚刚试了一下，没问题的，能抓到。

你先确认一下你手机root没有，确认证书配置好了没有，如果这两个都没问题，那就是没有抓对url。

**Comment by MySummerEgg** [comment]
难得大佬回复即时,我用的iphone,fiddler抓包,参数和返回全是密文
![jmsj](https://github.com/user-attachments/assets/af6a5255-f019-42f9-a616-670b2e568293)

**Comment by MySummerEgg** [comment]
感谢大佬及时回复,我用的iphone,fiddler抓包的,请求和返回全都是密文,这有解吗
![jmsj](https://github.com/user-attachments/assets/22fc9a49-cfb8-44e7-b539-9e42be90274e)

**Comment by BNDou** [comment]
login这个url本来就是加密的😂

**Comment by MySummerEgg** [comment]
> login这个url本来就是加密的😂

大佬有方法解开吗

**Comment by BNDou** [comment]
@MySummerEgg 我就是开发到这里被卡住了😁得需要安卓逆向的大佬了，这方面我不擅长，这个返回的数据只能针对寻宝次数有用，其实没多大用，能每日签到就行了

**Comment by MySummerEgg** [comment]
> @MySummerEgg 我就是开发到这里被卡住了😁得需要安卓逆向的大佬了，这方面我不擅长，这个返回的数据只能针对寻宝次数有用，其实没多大用，能每日签到就行了

ok,感谢大佬回复
