### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qq846511277** [BNDou/Auto_Check_In#7]
建议搞掌飞里面 每日寻宝 水大

**Comment by BNDou** [comment]
@qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下

**Comment by zy-xiaoao** [comment]
> @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下

这个我写了  num是你解锁地图的等级 你可以试试
def map(num):  # 设置你飞车解锁的地图， 1 2 3 4 5 6
    urls = 'https://bang.qq.com/app/speed/treasure/index'
    result = requests.get(urls, headers={}).text
    day = re.findall(r"window.mapInfo = eval\(\'\((.*)\)\'\);", result)
    dict = eval(day[0].encode('utf-8').decode('unicode_escape'))[f'{num}']
    for i in dict:
        if i['isdaji'] == 1:
            id = i['id']
            name = i['name']
            print(f'今日大吉地图是[{name}] id是[{id}]')
            return id

**Comment by zy-xiaoao** [comment]
> @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下

我现在遇到问题，我自己写的冒险，但是第二天在跑就显示   对不起，当天的寻宝次数已用完  不知道为何？重新抓token就没问题了。。。  你的脚本有这个问题吗？？？

**Comment by zy-xiaoao** [comment]
> @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下

而且变量只需要三个值，roleId&userId&token  Referer只需要前面的https://bang.qq.com/app/speed/treasure/index 有空可以交流下吗？  作者

**Comment by qq846511277** [comment]
> > @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下
> 
> 我现在遇到问题，我自己写的冒险，但是第二天在跑就显示 对不起，当天的寻宝次数已用完 不知道为何？重新抓token就没问题了。。。 你的脚本有这个问题吗？？？

掌飞登录之后有一个登录状态token1，类似签到、寻宝都是下面的分支，是通过token1分发的token2、token3。token2、token3就第二次刷新前面的就到期。

**Comment by qq846511277** [comment]
> > > @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下
> > 
> > 
> > 我现在遇到问题，我自己写的冒险，但是第二天在跑就显示 对不起，当天的寻宝次数已用完 不知道为何？重新抓token就没问题了。。。 你的脚本有这个问题吗？？？
> 
> 掌飞登录之后有一个登录状态token1，类似签到、寻宝都是下面的分支，是通过token1分发的token2、token3。token2、token3就第二次刷新前面的就到期。

token1获取下面token的加密方式，我等应该不行

**Comment by zy-xiaoao** [comment]
> > > @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下
> > 
> > 
> > 我现在遇到问题，我自己写的冒险，但是第二天在跑就显示 对不起，当天的寻宝次数已用完 不知道为何？重新抓token就没问题了。。。 你的脚本有这个问题吗？？？
> 
> 掌飞登录之后有一个登录状态token1，类似签到、寻宝都是下面的分支，是通过token1分发的token2、token3。token2、token3就第二次刷新前面的就到期。

有刷新这个的吗？我没找到，url是啥？？？  我现在遇到的问题就是第二天不能刷新登录状态，导致冒险第二天不能正常跑了

**Comment by BNDou** [comment]
@zy-xiaoao 我前几天上传了一版固定地图的，也是第二天报错让我删了，你可以查看我历史更新。
我抓的是三个链接，分别是模拟手动寻宝的过程①开始寻宝②结束寻宝③领取，到次日①②可以用，③就报错了，③的url好像也是动态的，第二天奖励获取不到了。

**Comment by BNDou** [comment]
> > @qq846511277 可以搞，但是今日大吉分配到哪个图抓不到😂你有没有办法，可以提出参考一下
> 
> 这个我写了  num是你解锁地图的等级 你可以试试
> def map(num):  # 设置你飞车解锁的地图， 1 2 3 4 5 6
>     urls = 'https://bang.qq.com/app/speed/treasure/index'
>     result = requests.get(urls, headers={}).text
>     day = re.findall(r"window.mapInfo = eval\(\'\((.*)\)\'\);", result)
>     dict = eval(day[0].encode('utf-8').decode('unicode_escape'))[f'{num}']
>     for i in dict:
>         if i['isdaji'] == 1:
>             id = i['id']
>             name = i['name']
>             print(f'今日大吉地图是[{name}] id是[{id}]')
>             return id

谢谢，我星期天抽空试试，有结果联系您

**Comment by zy-xiaoao** [comment]
> @zy-xiaoao 我前几天上传了一版固定地图的，也是第二天报错让我删了，你可以查看我历史提交[XunBao](https://github.com/BNDou/Auto_Check_In/commit/4807970e8ec1d59a9d4e06092f0e3e64d296a8bb)。 我抓的是三个链接，分别是模拟手动寻宝的过程①开始寻宝②结束寻宝③领取，到次日①②可以用，③就报错了，③的url好像也是动态的，第二天奖励获取不到了。

我是第二天不能重置冒险次数

**Comment by BNDou** [comment]
@zy-xiaoao 我已提交。其实我是边学边开发，技术和逻辑方面应用的不是太灵活，不过你分享的代码针不戳，给我带来很大的灵感，谢谢😄
另外开启寻宝和结束寻宝目前无异常，但是领取奖励的那个url还是不能持续使用，当天的url只能当天用，次日就异常了，这里不会整了，后续慢慢研究。如果你有想法可以直接申请提交一版，再次感谢！

**Comment by BNDou** [comment]
@zy-xiaoao 
1.是不是青龙py依赖里面没添加bs4库，如下图：<img src="https://user-images.githubusercontent.com/67632799/223600636-eec299ef-bac3-4fb2-b702-1de4d8843342.png" width="40%">

2.这个就相当于是模拟手动点击，我之前app上面卡0点进去大多数情况进去次数是0，退了app重进次数就出来了，不刷新的原因或许是掌飞自己的逻辑bug，就像有时候开始寻宝后没有奖励弹窗，我自己测试出来的解决办法就是不能卡0点，稍微慢几秒再运行，就会刷新出次数，只不过领取奖励那个环节我目前还做不出来😄下面是我运行的log，第一张是有次数的时候，第二张没次数了<img src="https://user-images.githubusercontent.com/67632799/223603468-db509bc5-5a78-4bcf-98cc-3dc5870d2776.png" width="40%"><img src="https://user-images.githubusercontent.com/67632799/223603579-514df6fe-4bf0-42b8-afcd-5ed2ca2dafa6.png" width="40%">

**Comment by qq846511277** [comment]
> @zy-xiaoao 1.是不是青龙py依赖里面没添加bs4库，如下图：![](https://user-images.githubusercontent.com/67632799/223600636-eec299ef-bac3-4fb2-b702-1de4d8843342.png)
> 
> 2.这个就相当于是模拟手动点击，我之前app上面卡0点进去大多数情况进去次数是0，退了app重进次数就出来了，不刷新的原因或许是掌飞自己的逻辑bug，就像有时候开始寻宝后没有奖励弹窗，我自己测试出来的解决办法就是不能卡0点，稍微慢几秒再运行，就会刷新出次数，只不过领取奖励那个环节我目前还做不出来😄下面是我运行的log，第一张是有次数的时候，第二张没次数了 ![](https://user-images.githubusercontent.com/67632799/223603468-db509bc5-5a78-4bcf-98cc-3dc5870d2776.png) ![](https://user-images.githubusercontent.com/67632799/223603579-514df6fe-4bf0-42b8-afcd-5ed2ca2dafa6.png)
意思就是 脚本还是可以用的？我看寻宝出车时间不固定的，随机的
，

**Comment by BNDou** [comment]
@qq846511277 不能，半成品，只能浪费寻宝次数，奖励飞走了😂
